### ISSUE TITLE
Logging in as a new user shows an unrelated course in the breadcrumbs

### ISSUE THREAD

**Issue by canstudios-scottd** [adapt-security/adapt-authoring-ui#105]
Logging in as a user shows the course just created by another user when logging in on the breadcrumbs but does not show on the dashboard.

Steps to reproduce:

As user 1 (admin) create user 2
Create a new course and give it a unique title
Log in as user 2
Notice that the title of the course creates by user 1 shows on the dashboard in the breadcrumbs menu. However the course itself does not show on the dashboard.

**Comment by taylortom** [comment]
Fixed

**Comment by scottdarcydigital** [comment]
Tested and Verified on https://testing.kineoadapt.com/#/dashboard
