### ISSUE TITLE
Copying a block copies to incorrect location

### ISSUE THREAD

**Issue by canstudios-scottd** [adapt-security/adapt-authoring-ui#106]
In the page editor, when copying a block the pasted location is always above or below the original item. In some cases is incorrect eg: having 10 blocks in a single article, copying the 5th one and attempting to copy it to be the 1st item results in it being the 4th.

**Comment by canstudios-scottd** [comment]
@tomgreenfield comment re-added

"See adapt-security/adapt-authoring#296."

**Comment by scottdarcydigital** [comment]
Update : Attempting to copy a block results in the error message "Cannot copy component, there are no free locations" which seems odd. Paste buttons are then available, but attempting to click on one shows the "An error occurred during paste. Please try again." error message and the block is not copied.

**Comment by joe-allen-89** [comment]
I'm getting a slightly different error than the one above. 

When attempting to copy a block I get the "Cannot copy component, there are no free locations" error, and the paste buttons appear. However when I press paste, the block pastes into the correct location, but strangely the Expand/Collapse buttons at the top of the page duplicate. No errors in console.

**Comment by chris-steele** [comment]
Currently unable to replicate the issues described. @taylortom are you seeing any problems?
