### ISSUE TITLE
Cannot reorder elements on the page editor by clicking and dragging

### ISSUE THREAD

**Issue by canstudios-scottd** [adapt-security/adapt-authoring-ui#107]
Usually it is possible to change the order of blocks and articles by clicking and dragging them. However this does not seem to work as expected. Sometimes they will be added to the bottom of the hierarchy.

**Comment by canstudios-scottd** [comment]
@tomgreenfield comment re-added

"See adapt-security/adapt-authoring#296."

**Comment by taylortom** [comment]
Fixed

**Comment by scottdarcydigital** [comment]
Update this now works, but a refresh is required in order to see the change

**Comment by joe-allen-89** [comment]
After dropping the block into a new slot the page jumps to the top which isn't ideal but the change in order isn't visible until after you refresh the page.

**Comment by taylortom** [comment]
Closing, refresh issue has been logged here: https://github.com/adapt-security/adapt-authoring-ui/issues/192
