### ISSUE TITLE
When copying a page and/or article items re-order themselves

### ISSUE THREAD

**Issue by canstudios-scottd** [adapt-security/adapt-authoring-ui#109]
This is occurring intermittently, but is more common on an article.

Steps to reproduce:

Create and article on a page which contains a few different components
Copy a couple of those components to other blocks in that article
Make a note of the order
Copy the article
Notice that some of the components have changed order in the copy
Repeat this with a few new and a few copied components within the same block on another article

**Comment by canstudios-scottd** [comment]
@tomgreenfield comment re-added

"See adapt-security/adapt-authoring#296."

**Comment by taylortom** [comment]
Should now be fixed

**Comment by joe-allen-89** [comment]
Tested with various comps in an article including copied blocks. Duplicated the article and all seem to be in the correct order. Closing as fixed.
