### ISSUE TITLE
A-Z filtering on courses not working

### ISSUE THREAD

**Issue by canstudios-scottd** [adapt-security/adapt-authoring-ui#112]
The A-Z filter is not working as expected, with Z-A in particular showing no application to the order of the courses. This occurs regardless of the grid of list layout which itself seems to be working fine.

Steps to reproduce:

Create a few courses which have a range of different titles that can are intended for A-Z filtering making sure to include upper and lower case characters in their titles
Enter list view
Attempt to use the A-Z and Z-A filters
Enter grid view
Attempt to use the A-Z and Z-A filters
Notice how the filters do not work as expected

**Comment by joe-allen-89** [comment]
The A-Z filtering on courses is not quite working as expected. I have three courses and when switching between A-Z & Z-A only the two most recent courses are sorted. The oldest (also imported) course is not sorted as expected. This is consistent with both list and grid views.

**Comment by joe-allen-89** [comment]
On closer inspection this seems to be an issue with imported courses not being included in the sorting. I've added an additional course from the create course button and all 3 courses created in the tool are being sorted as expected. The course that was imported is not being included in the sorting.

**Comment by taylortom** [comment]
I'm not able to replicate this one now

**Comment by joe-allen-89** [comment]
All courses are sorting as expected
