### ISSUE TITLE
Filter by tag not working

### ISSUE THREAD

**Issue by canstudios-scottd** [adapt-security/adapt-authoring-ui#114]
On the main dashboard the search field for the tags allows the user to enter values, but this does not filter courses and does not come up with the usually 'suggested' tags as a dropdown to the search field

**Comment by taylortom** [comment]
Fixed from the UI side, now need an API fix to allow the query to work as expected

**Comment by taylortom** [comment]
Fixed

**Comment by joe-allen-89** [comment]
Tested and seems to filter the course by tag as expected.
