### ISSUE TITLE
Course Preview image is not working

### ISSUE THREAD

**Issue by fkcailiniyazi** [adapt-security/adapt-authoring-ui#117]
I can see the course preview Image in the project settings, but from the dashboard, I can't see it.

**Comment by taylortom** [comment]
The preview image is working for me. Could you please try updating and see if this is something that's been fixed? :)

**Comment by fkcailiniyazi** [comment]
Hi Tom, I've tested it on the testing server.

![image](https://user-images.githubusercontent.com/54360982/113141088-89e91380-9229-11eb-86db-63666bad4383.png)

**Comment by fkcailiniyazi** [comment]
This was the error message:
`testing.kineoadapt.com/:1 GET https://testing.kineoadapt.com/api/assets/serve/course/assets/f386b8a7b3869a12a381a21d84c6dd39ef4a8862.jpg?thumb=true 404 (Not Found)
testing.kineoadapt.com/:1 GET https://testing.kineoadapt.com/api/assets/serve/course/assets/f386b8a7b3869a12a381a21d84c6dd39ef4a8862.jpg?thumb=true 404 (Not Found)`

**Comment by fkcailiniyazi** [comment]
I tested it again by creating a new course and this problem is not shown, maybe this was already fixed but somehow that existed in the old course. I've already deleted the old courses and I'm closing this issue.
