### ISSUE TITLE
Thumbnails should probably be a bit higher resolution

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring-ui#123]
And preferably configurable via the config file

**Comment by fkcailiniyazi** [comment]
Which resolution by default should we have?

**Comment by fkcailiniyazi** [comment]
Just noticed that this line is related to this issue:
[https://github.com/adapt-security/adapt-authoring-assets/blob/359931e379fa6a24833585d3b7ea39ef08aa93ee/conf/config.schema.json#L18](url)
