### ISSUE TITLE
how to install it?

### ISSUE THREAD

**Issue by hffei** [adapt-security/adapt-authoring-ui#125]
sorry, I am a adapt authoring user.  I don't know how to install this ui?

**Comment by taylortom** [comment]
Hi @hffei, this is an in-development major update to the existing [adapt_authoring](https://github.com/adaptlearning/adapt_authoring) UI, and can't be used with the older version. 

If you're interested in testing this alpha version when it's ready, let me know and I can provide instructions (the alpha release will likely be pretty unstable, and won't be suitable for production use for quite some time).

**Comment by hffei** [comment]
Nice


I'm interested in learning about this project。

2021年4月6日 下午5:38，Tom Taylor ***@***.******@***.***>> 写道：



Hi @hffei<https://github.com/hffei>, this is an in-development major update to the existing adapt_authoring<https://github.com/adaptlearning/adapt_authoring> UI, and can't be used with the older version.

If you're interested in testing this alpha version when it's ready, let me know and I can provide instructions (the alpha release will likely be pretty unstable, and won't be suitable for production use for quite some time).
