### ISSUE TITLE
Plugin upload should support GitHub format

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring-ui#136]
See https://github.com/adapt-security/adapt-authoring-ui/issues/87

**Comment by taylortom** [comment]
Fixed

**Comment by joe-allen-89** [comment]
@taylortom currently when uploading the github downloads, it says that the upload was successful, but when I go back to the components it's not listed. Works as expected if I unpack the github zip folder and only upload the contained folder.

**Comment by taylortom** [comment]
Fixed (🤞)

**Comment by joe-allen-89** [comment]
That seems to have done the job nicely. Tested with GMCQ zip and working as expected.
