### ISSUE TITLE
assetManagement Tags Field logs error message

### ISSUE THREAD

**Issue by memeteli** [adapt-security/adapt-authoring-ui#142]
When I try to add tags into an asset I've uploaded, I can see there is server error log at console:

`2021-08-30T08:33:38.126Z error server Error: Not found: GET /api/autocomplete/tag?term=add`

**Comment by taylortom** [comment]
Tags seem to be stored in the DB as expected

**Comment by joe-allen-89** [comment]
Tom your issue appears to be a separate issue, raised separately - https://github.com/adapt-security/adapt-authoring-ui/issues/237
