### ISSUE TITLE
Page Level Progress causes failure of loading course page

### ISSUE THREAD

**Issue by amaimaiti** [adapt-security/adapt-authoring-ui#161]
the page will hang out, the browses shows the error message from Page Level Progress plugin.
![image](https://user-images.githubusercontent.com/54360982/149958461-ed1c9360-ab71-4a11-9869-d41ef0800dc1.png)

**Comment by taylortom** [comment]
This should now be fixed

**Comment by joe-allen-89** [comment]
Course with PLP loading as expected without error.
