### ISSUE TITLE
There are some issues at copying a page in course structure

### ISSUE THREAD

**Issue by amaimaiti** [adapt-security/adapt-authoring-ui#162]
It shows error message and the add submenu will be covered with another button. After closing the modal and click page, we can't see any changes but if we force reload the page, we can see that the page was copied.

![image](https://user-images.githubusercontent.com/54360982/149963010-daf3549e-abec-43f1-88b4-341b35351c14.png)

![image](https://user-images.githubusercontent.com/54360982/149963027-34578b06-6a6b-413d-9aa2-239263f550f6.png)

**Comment by fkcailiniyazi** [comment]
I can't verify the fix at my side. I still see the error.

**Comment by canstudios-scottd** [comment]
The error is gone, however the new page is not visible until the user refreshes the page. @taylortom is this acceptable to close the issue?

**Comment by taylortom** [comment]
Closing, refresh issue has been logged here: https://github.com/adapt-security/adapt-authoring-ui/issues/192
