### ISSUE TITLE
Page Level Progress fails loading

### ISSUE THREAD

**Issue by amaimaiti** [adapt-security/adapt-authoring-ui#167]
At preview, Page Level Progress fails loading.

![image](https://user-images.githubusercontent.com/54360982/149937784-7c7e8a8d-9ea0-4dff-bb42-02230d6dc4c4.png)

**Comment by taylortom** [comment]
This should now be fixed

**Comment by joe-allen-89** [comment]
Course with PLP loading as expected without error.
