### ISSUE TITLE
Course import shows "Undefined Error" Message

### ISSUE THREAD

**Issue by amaimaiti** [adapt-security/adapt-authoring-ui#169]
By uploading a file, if it fails, will show "error.undefined" error message.

![image](https://user-images.githubusercontent.com/54360982/149917554-001f41d6-8873-44aa-8322-f4f07c310b97.png)

**Comment by taylortom** [comment]
Can't replicate this one, can you please retest and if it's still an issue, give a bit more info on the type of course you were trying to import (you can also attach the zip to this issue :))

**Comment by taylortom** [comment]
Closing this for now
