### ISSUE TITLE
Export Source & Publish Course leads to blank page

### ISSUE THREAD

**Issue by memeteli** [adapt-security/adapt-authoring-ui#172]
After clicking export button, we will not get the zip file and we will be redirected to a blank page as follows:
![image](https://user-images.githubusercontent.com/54360982/162743757-bb2b4c59-f92c-448e-a87b-f86a85665637.png)

And if we refresh the page, we will still get the blank page and the zip file will be downloaded.

**Comment by fkcailiniyazi** [comment]
Publish Course has the same behavior.

**Comment by fkcailiniyazi** [comment]
At local environment it works fine.

**Comment by taylortom** [comment]
Can't replicate now on the testing site, please confirm fixed :)

**Comment by fkcailiniyazi** [comment]
It looks like the problem is about the SSL certificate on the testing server, the browser shows me that the connection is not secure, but if I test in the local server or our testing server with a valid SSL certificate, it works fine.

**Comment by taylortom** [comment]
Seeing this one again

**Comment by joe-allen-89** [comment]
@taylortom as discussed this seems to be a config issue moving to needs reviewing for test on latest version with config updated.
