### ISSUE TITLE
Share a course to all the users doesn't work

### ISSUE THREAD

**Issue by amaimaiti** [adapt-security/adapt-authoring-ui#173]
At project settings, I've tried to select the course to share with all the users and saved the course, I can see that the selection was marked as "selected". Then I went to the shared course and I didn't see my course, so I went back to that course and "Share with all users" was unselected again: 
![image](https://user-images.githubusercontent.com/54360982/162746757-751bb50b-dd8c-446a-95f7-1bec87dd7f3e.png)

**Comment by taylortom** [comment]
I believe this is as designed. The shared course should still be listed in "My courses" if you are the creator, but should be shown in "Shared courses" for everyone else.
