### ISSUE TITLE
Incorrect choice to remove plugins from course

### ISSUE THREAD

**Issue by fkcailiniyazi** [adapt-security/adapt-authoring-ui#178]
Go to Dashboard → Course structure → Manage extensions, add some extensions and click 'Remove' button, we will see the popup window to select yes or no, we should click "yes" to remove the extension from the course, but when we click "yes", the extension will be stayed, but if we click "no", the extension will be removed.

![image](https://user-images.githubusercontent.com/54360982/163980280-cf3409ae-b20f-4197-86ec-244586e623a8.png)

**Comment by taylortom** [comment]
Fixed, closing as duplicate of https://github.com/adapt-security/adapt-authoring/issues/524
