### ISSUE TITLE
Page Level Progress logs error 

### ISSUE THREAD

**Issue by amaimaiti** [adapt-security/adapt-authoring-ui#179]
I've added Page Level Progress extension to the course and clicked the preview then I got this error message on browser:

![image](https://user-images.githubusercontent.com/54360982/163992691-a90ff7ec-84ba-469d-b969-36567cd54382.png)

There is no error message on console.

**Comment by taylortom** [comment]
This should be fixed

**Comment by joe-allen-89** [comment]
Course with PLP loading as expected without error.
