### ISSUE TITLE
Translation is missing at user manager

### ISSUE THREAD

**Issue by fkcailiniyazi** [adapt-security/adapt-authoring-ui#180]
The texts for user deletion selection are missing
![image](https://user-images.githubusercontent.com/54360982/163998955-9cd7b9a3-7e34-43dc-8966-0c83d28b621a.png)

**Comment by fkcailiniyazi** [comment]
And also for Error message by adding a user:
![image](https://user-images.githubusercontent.com/54360982/163999340-ca41ebfe-c943-4686-bf03-9bd00adb758f.png)
on Console:
warn lang missing key 'en.error.USER_REG_FAILED'

**Comment by taylortom** [comment]
Fixed
