### ISSUE TITLE
Role name is missing 

### ISSUE THREAD

**Issue by fkcailiniyazi** [adapt-security/adapt-authoring-ui#184]
When we go to User management, the name of roles is missing from the user lists, it will back if we use the role switches from the sidebar

![image](https://user-images.githubusercontent.com/54360982/168597133-2e63e646-797f-4dc3-8018-26a80e132450.png)

Steps to reproduce:

1. Go to User management page
2. Click the space under Role section
3. Then turn on and turn off the switch from sidebar

![image](https://user-images.githubusercontent.com/54360982/168597510-8db11b9a-fcab-483b-b96b-f7cdc96d3e34.png)

Environment:
Windows 10 Pro
node v16.13.1
npm 8.5.2

**Comment by taylortom** [comment]
This should be fixed
