### ISSUE TITLE
Transfer courses by user deletion should be happened only if the target user exists

### ISSUE THREAD

**Issue by fkcailiniyazi** [adapt-security/adapt-authoring-ui#185]
As my understanding, if a user is being deleted, we can select if its courses will be transferred to another user, if we select 'yes', we will get a confirmation window to enter an email address. In our test, even we enter some random emails which are not exists in the database, and they can be accepted but at the end the courses will be deleted with the user.

I think it is better the courses should be transferred only when the target email is registered in ATT otherwise the "transfer course" action should be cancelled.

Steps to reproduce:
1. create some users
2. create some courses using different users
3. go to user management and click delete user button
4. select "transfer all the courses to another user"
5. enter a random email and click confirmation

Environment:
Windows 10 Pro
node v16.13.1
npm 8.5.2

**Comment by taylortom** [comment]
Fixed, added validation to check this.

Also see https://github.com/adapt-security/adapt-authoring/issues/530
