### ISSUE TITLE
Should the only Super User be able to delete itself? 

### ISSUE THREAD

**Issue by memeteli** [adapt-security/adapt-authoring-ui#186]
During the tests, I tried to delete a superuser account that I've used to log in to the local environment, and it is deleted, now I have to create a new user manually. I think if there are no other super users in the system, the only user shouldn't be able to delete itself. 

Steps to reproduce:

1. Go to the User management page
2. Delete the superuser which is used to log in
3. Refresh the page

Environment:
Windows 10 Pro
node v16.13.1
npm 8.5.2

**Comment by taylortom** [comment]
There should also be an API-level restriction

**Comment by taylortom** [comment]
Fixed
