### ISSUE TITLE
A scrollbar appears unexpectedly on the login page

### ISSUE THREAD

**Issue by memeteli** [adapt-security/adapt-authoring-ui#188]
A scrollbar appears unexpectedly on the login page of the testing server and it will disappear as we start to type. 

![image](https://user-images.githubusercontent.com/54360982/172366743-00dd0daa-4395-4c5e-8444-6c409013ef14.png)

**Comment by taylortom** [comment]
Can't replicate this one

**Comment by joe-allen-89** [comment]
I can replicate this in Chrome and Edge, but no issue with Firefox. Getting a couple of errors which may be the cause of issue. 

![image](https://user-images.githubusercontent.com/85872286/189174906-264ab9ce-e6ed-4532-b652-b372cb2eb04c.png)

As soon as the screen is resized/dev tools opened the scroll bars disappear, as well as when you start typing. Strangely they also seem to disappear when you click to another tab and back.

**Comment by chris-steele** [comment]
I'm unable to replicate this on https://testing.kineoadapt.com/#user/login or locally
