### ISSUE TITLE
Not able to remove last tag

### ISSUE THREAD

**Issue by joe-allen-89** [adapt-security/adapt-authoring-ui#241]
### What happened?

Able to add and remove tags as expected but when trying to remove the last tag and saving it does not remove it. 

### Steps to reproduce

Add tags to an asset and save, edit it and try to remove all the assets. 

### Authoring tool version

Latest

**Comment by chris-steele** [comment]
+1

Removed last tag (3rd of 3) and saved - works fine.
Removed remaining two tags and saved - works fine.
