### ISSUE TITLE
Question feedback popup missing

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring-ui#266]
**Reported by Kineo QA**

### What happened?

**This seems to apply to all feedback popups, including Sliders**

When I've created an MCQ and added all the content, including the feedback text, and I've set the course up to show feedback, then the feedback popup doesn't actually appear when I review the course - clicking the 'Show feedback' button has no response.

Note, this seems to only happen if I'd made a course from scratch. If I copied a course that's been set up - I copied Pete's - then it doesn't happen.

### Authoring tool version

rc.3

**Comment by joe-allen-89** [comment]
As suggested possibly a tutor problem as can't be replicated with.
