### ISSUE TITLE
API erroring when fetching more than 2 pages of content.

### ISSUE THREAD

**Issue by joe-allen-89** [adapt-security/adapt-authoring-ui#275]
### What happened?

When trying to load the third page of content the apiCollection gets stuck in an infinte loop throwing constant errors (shown below). The regular expression in fetch isn't only pulling the next page but also the previous leading to the issue.

### Steps to reproduce

Create a course with more than 200 items. 

### Authoring tool version

rc4

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```sh
2024-01-18T14:25:02.496Z warn content failed to parse query page param 'undefined', SyntaxError: Unexpected token > in JSON at position 1
```

**Comment by taylortom** [comment]
FYI you can reduce the page size for easier testing using: 
```js
{
   // other config omitted
  'adapt-authoring-ap': {
    defaultPageSize: X
  }
}
```

**Comment by taylortom** [comment]
Works for me :fire:
