### ISSUE TITLE
Search by tag not restored after search by name

### ISSUE THREAD

**Issue by chris-steele** [adapt-security/adapt-authoring-ui#291]
### What happened?

I filtered courses using search by tag. I then filtered courses using search by name, which overrides search by tag (it is not a compound filter). The tag parameter I chose remains, however.

When I cleared the search by name parameter, the results were not filtered by tag, despite the tag parameter remaining.

### Expected behaviour

When I search by name any selected tags should be removed (or vice versa).

OR

The filter should be compound: i.e. if there are tags selected and a parameter given to search by name then the matching courses should satisfy both queries.

**Comment by taylortom** [comment]
I would expect the filters to remain applied until removed (or on navigate away)

**Comment by chris-steele** [comment]
@taylortom should courses be filtered by tag AND name or should name continue to override tag?

**Comment by taylortom** [comment]
Yes, I think all applied filters should be working together

**Comment by taylortom** [comment]
Have discussed, and the following was agreed:
- Filters should be compound
- Filters should only persist across sessions (not after reload/logout etc)

**Comment by chris-steele** [comment]
search and tags now persist correctly across sessions, though note that reload/logout does not affect browser session.

> A page session lasts as long as the tab or the browser is open, and survives over page reloads and restores. 

Ref: https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage

**Comment by joe-allen-89** [comment]
Tested on - https://v1testing.uat.kineoadapt.com/#/projects

The filters don't currently seem to be compounding, they seem to work by showing courses that fit the most recent search criteria. 

When I first filter by tag the filter works as expected:
![Image](https://github.com/user-attachments/assets/d4885278-e788-44b9-ab5f-b0c9f83fe93d)

But when I add to search by name it ignores the tag filter: 
![Image](https://github.com/user-attachments/assets/c11657ac-44df-4413-b763-204e1b18fae2)

And if you remove either of the filters all are removed and all the courses are shown:
![Image](https://github.com/user-attachments/assets/051fbeb0-8c4b-471a-83a0-22f52912925e)

**Comment by taylortom** [comment]
@joe-allen-89 apologies this one hadn't actually been merged, should be ready now.

**Comment by joe-allen-89** [comment]
Works as expected on v1Testing
