### ISSUE TITLE
Shared courses do not appear in shared dashboard

### ISSUE THREAD

**Issue by chris-steele** [adapt-security/adapt-authoring-ui#310]
### What happened?

https://github.com/cgkineo/adapt-authoring/issues/26

### Steps to reproduce

https://github.com/cgkineo/adapt-authoring/issues/26

### Authoring tool version

https://github.com/cgkineo/adapt-authoring/issues/26

**Comment by taylortom** [comment]
Closing this, as functionality will be merged in a forthcoming release.
