### ISSUE TITLE
Fix user edit roles

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring-ui#4]

**Comment by taylortom** [comment]
Done

**Comment by deltanetdan** [comment]
Roles data is not populate on first loading the user management page. Editing a user record gives this console error:
![Screenshot 2022-04-22 at 13 56 14](https://user-images.githubusercontent.com/4161219/164718941-75adc7e2-101d-4168-a1a0-4de3dfa54372.png)

**Comment by joe-allen-89** [comment]
When first navigating to user management page a blank error pops up on page. 

Role data is populated on screen but when trying to change the role of the test account the following error is shown "{"code":"ENDPOINT_NOT_FOUND","message":"Endpoint /api/users/role/unassign/ does not exist"}", no console errors.

**Comment by taylortom** [comment]
Can't replicate any issues with roles now

**Comment by joe-allen-89** [comment]
Fixed, no errors on load and created users storing as expected.
