### ISSUE TITLE
Unable to save project settings due to customStyle Syntax error

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring-ui#59]

**Comment by tomgreenfield** [comment]
Was going to mention – looks like the logic was broken in your [refactor](https://github.com/adapt-security/adapt-authoring-ui/commit/26dc69fdf920afea7ffffebf6d34da6ed9d2c982#diff-d4dc46596fbe7626cb2ac3555c144db7e76fe386af8099f68cce15a622045819R54).

**Comment by taylortom** [comment]
Fixed

**Comment by canstudios-scottd** [comment]
Passed on Can Studios QA testing.
