### ISSUE TITLE
Unable to rename course

### ISSUE THREAD

**Issue by Christine-Yates** [adapt-security/adapt-authoring-ui#61]
When trying to rename a duplicated course, I'm receiving the following error message: 
![rename-error](https://user-images.githubusercontent.com/24430924/109000057-dd58c680-76ab-11eb-983b-08bdd8a15375.JPG)

**Comment by taylortom** [comment]
Think this is due to https://github.com/adapt-security/adapt-authoring/issues/381, but will leave this open for now,

**Comment by taylortom** [comment]
Fixed
