### ISSUE TITLE
When typing in a single line text field (eg title, displayTitle) the value reverts to the saved state if I press enter after typing

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adapt-security/adapt-authoring-ui#70]
To reproduce:

- Create a new course
- The "title" field will contain text "Untitled"
- Type something else in the title field and press enter
- Notice that the field has reverted to "Untitled"

**Comment by taylortom** [comment]
It looks like the revert button has focus, will look into

**Comment by joe-allen-89** [comment]
I've tested this in various browsers and the only way I can get it to reset by pressing enter is to shift-tab to the reset button first, I'd say this isn't an issue so happy to close. @taylortom thoughts?

**Comment by taylortom** [comment]
Just to recap: the only way I can replicate this is to put some text into the first text field in the form, then go to any text field and press enter. The first text field is emptied.
