### ISSUE TITLE
Super admins can view courses that aren't shared with them

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adapt-security/adapt-authoring-ui#71]
To reproduce:

- You will need two super admin accounts (A & B)
- As A, create a new course and save it
- As B, notice you can view both the AT editor for A's course and a link to a preview of the course

It's unclear whether this is an issue, or whether it is acceptable for super admins. Behaviour for other roles should also be confirmed.

**Comment by chucklorenz** [comment]
I think some role should have the ability to see every course and to transfer ownership of the course from one user to another. Useful when someone leaves the team/company and when a course is imported then assigned to a user. Seems inline with Super Admin.

**Comment by taylortom** [comment]
Filtering has been fixed as per legacy. Will open a separate issue for @chucklorenz's suggestion, as I think this is a useful (but separate) feature.
