### ISSUE TITLE
Unable to edit assets

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring-ui#77]
Recieve 404 for 
```
GET /api/assets/ASSET_ID
```

**Comment by taylortom** [comment]
Something wrong with the assets API on testing site in general, seem to be getting all 404s. Need to test this locally to replicate.

**Comment by taylortom** [comment]
Fixed.

Have added the above route.

**Comment by canstudios-scottd** [comment]
This passes testing, aside from the tags is not yet working. Related to https://github.com/adapt-security/adapt-authoring-ui/issues/116
