### ISSUE TITLE
Unable to upload plugins

### ISSUE THREAD

**Issue by Christine-Yates** [adapt-security/adapt-authoring-ui#87]
When trying to add a component or extension, I'm receiving the error 'Plugin upload failed. Received unexpected file type, expected application/zip'

**Comment by taylortom** [comment]
I'm not able to replicate this one either locally or on testing.kineoadapt. All plugins I've tested have been zipped without a containing folder (downloads from github won't work) - this could be the issue?

This being said, I suggest we fix this so that zip downloads from github _do_ work
