### ISSUE TITLE
A-Z filtering on courses not working

### ISSUE THREAD

**Issue by scottdarcydigital** [adapt-security/adapt-authoring-ui#91]
The A-Z filter is not working as expected, with Z-A in particular showing no application to the order of the courses. This occurs regardless of the grid of list layout which itself seems to be working fine. 

Steps to reproduce:
1. Create a few courses which have a range of different titles that can are intended for A-Z filtering making sure to include upper and lower case characters in their titles
2. Enter list view
3. Attempt to use the A-Z and Z-A filters
4. Enter grid view  
5. Attempt to use the A-Z and Z-A filters
6. Notice how the filters do not work as expected

**Comment by canstudios-nicolaw** [comment]
Raised with wrong github account. Will be re-raised
