### ISSUE TITLE
When copying a page and/or article items re-order themselves

### ISSUE THREAD

**Issue by scottdarcydigital** [adapt-security/adapt-authoring-ui#94]
This is occurring intermittently, but is more common on an article.

Steps to reproduce:
1. Create and article on a page which contains a few different components
2. Copy a couple of those components to other blocks in that article
3. Make a note of the order
4. Copy the article
5. Notice that some of the components have changed order in the copy
6. Repeat this with a few new and a few copied components within the same block on another article

**Comment by tomgreenfield** [comment]
See https://github.com/adapt-security/adapt-authoring/issues/296.

**Comment by canstudios-nicolaw** [comment]
Raised with wrong github account. Will be re-raised
