### ISSUE TITLE
HTML tags and information is stripped from the CKEditor

### ISSUE THREAD

**Issue by scottdarcydigital** [adapt-security/adapt-authoring-ui#95]
When the source button is used to enter html information into the CKEditor of a component it initially works, including on the course preview. However, when the user attempts to add/edit this again the html has been stripped from the field and only shows basic text with </br> tags where appropriate.

**Comment by tomgreenfield** [comment]
Hi @scottdarcydigital, this is the standard behaviour of CKEditor; see https://github.com/adaptlearning/adapt_authoring/issues/1619.

Overrides be added to the server configuration e.g.
```js
"adapt-authoring-ui": {
  "ckEditor": {
    "extraAllowedContent": "span(*)[*]{*}"
  }
}
```

**Comment by canstudios-nicolaw** [comment]
We have a different configuration at Can - closing as this isn't an issue
