### ISSUE TITLE
 Cannot reorder elements on the page editor by clicking and dragging

### ISSUE THREAD

**Issue by scottdarcydigital** [adapt-security/adapt-authoring-ui#96]
Usually it is possible to change the order of blocks and articles by clicking and dragging them. However this does not seem to work as expected. Sometimes they will be added to the bottom of the hierarchy.

**Comment by tomgreenfield** [comment]
See https://github.com/adapt-security/adapt-authoring/issues/296.

**Comment by canstudios-nicolaw** [comment]
Raised with wrong github account. Will be re-raised
