### ISSUE TITLE
Copying a block copies to incorrect location

### ISSUE THREAD

**Issue by scottdarcydigital** [adapt-security/adapt-authoring-ui#97]
In the page editor, when copying a block the pasted location is always above or below the original item.  In some cases is incorrect eg: having 10 blocks in a single article, copying the 5th one and attempting to copy it to be the 1st item results in it being the 4th.

**Comment by tomgreenfield** [comment]
See https://github.com/adapt-security/adapt-authoring/issues/296.

**Comment by canstudios-nicolaw** [comment]
Raised with wrong github account. Will be re-raised
