### ISSUE TITLE
Logging in as a new user shows an unrelated course in the breadcrumbs 

### ISSUE THREAD

**Issue by scottdarcydigital** [adapt-security/adapt-authoring-ui#98]
Logging in as a user shows the course just created by another user when logging in on the breadcrumbs but does not show on the dashboard.

Steps to reproduce: 
1. As user 1 (admin) create user 2
2. Create a new course and give it a unique title
3. Log in as user 2
4. Notice that the title of the course creates by user 1 shows on the dashboard in the breadcrumbs menu. However the course itself does not show on the dashboard.

**Comment by canstudios-nicolaw** [comment]
Raised with wrong github account. Will be re-raised
